# Generated by Django 4.2.7 on 2023-12-19 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0002_category_alter_store_image_url_alter_store_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='store_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='store',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stores', to='rate.category'),
        ),
    ]
