# Generated by Django 4.2.7 on 2023-12-19 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0004_remove_category_store_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='stores',
            field=models.ManyToManyField(related_name='categories', to='rate.store'),
        ),
        migrations.AlterField(
            model_name='store',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_categories', to='rate.category'),
        ),
    ]
