# Generated by Django 4.2.7 on 2023-12-20 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0006_searchbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchbox',
            name='store_name',
            field=models.CharField(default='Belly', max_length=100),
        ),
        migrations.AlterField(
            model_name='searchbox',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
