# Generated by Django 4.2.7 on 2023-12-20 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0007_searchbox_store_name_alter_searchbox_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='followers',
            field=models.ManyToManyField(related_name='following', to='rate.store'),
        ),
    ]
