# Generated by Django 4.2.7 on 2023-12-21 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0009_remove_storeprofile_following_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storefollowers',
            name='followers_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
