# Generated by Django 4.2.7 on 2023-12-21 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0010_storefollowers_followers_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='storefollowers',
            name='followers_count',
        ),
    ]
