# Generated by Django 4.2.7 on 2023-12-22 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0012_alter_userprofile_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritestore',
            name='user_profile',
        ),
        migrations.AddField(
            model_name='user',
            name='image_url',
            field=models.URLField(default='https://cdn4.iconfinder.com/data/icons/music-ui-solid-24px/24/user_account_profile-2-512.png'),
        ),
        migrations.AddField(
            model_name='user',
            name='introduction',
            field=models.CharField(default='My introduction', max_length=200),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
