# Generated by Django 4.2.7 on 2023-12-22 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0013_remove_favoritestore_user_profile_user_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='image_url',
            field=models.URLField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRBp_jLbdg8HuM0rkuzxlGxfyB8cswrmAlFVUHdXckCgfEk4HH-Jj-HnTU4Mnu8T0VYMxc&usqp=CAU'),
        ),
    ]
