# Generated by Django 4.2.7 on 2023-12-22 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0014_alter_review_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.TextField(default='My review content is empty', max_length=500),
        ),
    ]
