# Generated by Django 4.2.7 on 2023-12-22 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0015_alter_review_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.TextField(max_length=500),
        ),
    ]
