# Generated by Django 4.2.7 on 2023-12-22 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0016_alter_review_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
